version: "3"

services:
  db:
    image: postgres:14.5-alpine
    container_name: oss-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env.txt
    networks:
      - v-network

  redis:
    image: redis:alpine
    restart: always
    container_name: oss-redis
    command: redis-server --appendonly yes
    volumes:
      - ./_redis_data:/var/lib/redis
      - ./redis/rc.local:/etc/rc.local
    networks:
      - v-network

  web:
    image: project/oss:0.0.1
    restart: always
    container_name: oss-web
    volumes:
      - ./sock/:/sock/
      - ./project/:/usr/src/app/
      - ./logs/:/logs/
      - ./static/:/static/
    command: sh entrypoint.sh
    env_file:
      - env.txt
    networks:
      - v-network

  nginx:
    image: nginx:latest
    container_name: oss-nginx
    restart: always
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./react/dist:/var/www/frontend
      - ./static/:/var/www/static
      - ./sock/:/sock/
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
    networks:
      - v-network

networks:
  v-network:
    external: false


volumes:
  postgres_data: